### ISSUE TITLE
Draw lasso mode (more continuous polygon selection based on drag interaction)

### ISSUE THREAD

**Issue by keller-mark** [uber/nebula.gl#361] opened 2020-03-23 19:22 UTC
#### Background
To draw a very irregular polygon with the `DrawPolygonMode`, one needs to click many times, which can be slow. It would be great to have a more continuous method of selecting a polygon, based on dragging the mouse (similar to the photoshop lasso tool).

#### To Do List
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Test

**Comment by supersonicclay** [comment] 2020-03-23 19:29
Thanks for the request. This would be a nice enhancement we could either add to `DrawPolygonMode` or add an additional mode for. Let me know if you'd be interested in contributing and I can point you in a direction to implement this.

Duplicate of #172

**Closed by supersonicclay** 2020-03-23 19:29 UTC
