### ISSUE TITLE
Nebula not working with newly scaffolded Fusion App

### ISSUE THREAD

**Issue by trevorwhealy** [uber/nebula.gl#64] opened 2018-08-30 20:13 UTC
Steps to Reproduce:
```
yarn create fusion-app demo
cd demo
touch src/pages/demo.js
```

Add demo.js to root.js and provision a route for it
Code for the demo.js, mostly copied from the example of editableGeoJsonLayer
https://github.com/trevorwhealy/nebula-fusion-incompatibility/blob/master/src/pages/demo.js

```
yarn add deck.gl react-map-gl nebula.gl
yarn dev
```

<img width="652" alt="screen shot 2018-08-30 at 12 56 56 pm" src="https://user-images.githubusercontent.com/14946478/44876488-1c7e3c00-ac56-11e8-8cb6-249a704e8056.png">

Errors:
```
Fusion.js
Let's Get Started
ERROR in ./node_modules/@turf/difference/index.mjs 52:22-35
Can't import the named export 'diff' from non EcmaScript module (only default export is available)
 @ ./node_modules/nebula.gl/dist-es6/lib/deck-renderer/deck-drawer.js
 @ ./node_modules/nebula.gl/dist-es6/index.js
 @ ./src/pages/demo.js
 @ ./src/root.js
 @ ./src/main.js
 @ ./node_modules/fusion-cli/entries/client-entry.js
 @ multi (webpack)-hot-middleware/client.js?name=client ./node_modules/fusion-cli/entries/client-entry.js
ERROR in ./node_modules/@turf/difference/index.mjs 50:23-30
Can't import the named export 'feature' from non EcmaScript module (only default export is available)
 @ ./node_modules/nebula.gl/dist-es6/lib/deck-renderer/deck-drawer.js
 @ ./node_modules/nebula.gl/dist-es6/index.js
 @ ./src/pages/demo.js
 @ ./src/root.js
 @ ./src/main.js
 @ ./node_modules/fusion-cli/entries/client-entry.js
 @ multi (webpack)-hot-middleware/client.js?name=client ./node_modules/fusion-cli/entries/client-entry.js
ERROR in ./node_modules/@turf/difference/index.mjs 72:8-19
Can't import the named export 'flattenEach' from non EcmaScript module (only default export is available)
 @ ./node_modules/nebula.gl/dist-es6/lib/deck-renderer/deck-drawer.js
 @ ./node_modules/nebula.gl/dist-es6/index.js
 @ ./src/pages/demo.js
 @ ./src/root.js
 @ ./src/main.js
 @ ./node_modules/fusion-cli/entries/client-entry.js
 @ multi (webpack)-hot-middleware/client.js?name=client ./node_modules/fusion-cli/entries/client-entry.js
ERROR in ./node_modules/@turf/difference/index.mjs 42:16-23
Can't import the named export 'getGeom' from non EcmaScript module (only default export is available)
 @ ./node_modules/nebula.gl/dist-es6/lib/deck-renderer/deck-drawer.js
 @ ./node_modules/nebula.gl/dist-es6/index.js
 @ ./src/pages/demo.js
 @ ./src/root.js
 @ ./src/main.js
 @ ./node_modules/fusion-cli/entries/client-entry.js
 @ multi (webpack)-hot-middleware/client.js?name=client ./node_modules/fusion-cli/entries/client-entry.js
ERROR in ./node_modules/@turf/difference/index.mjs 43:16-23
Can't import the named export 'getGeom' from non EcmaScript module (only default export is available)
 @ ./node_modules/nebula.gl/dist-es6/lib/deck-renderer/deck-drawer.js
 @ ./node_modules/nebula.gl/dist-es6/index.js
 @ ./src/pages/demo.js
 @ ./src/root.js
 @ ./src/main.js
 @ ./node_modules/fusion-cli/entries/client-entry.js
 @ multi (webpack)-hot-middleware/client.js?name=client ./node_modules/fusion-cli/entries/client-entry.js
ERROR in ./node_modules/@turf/difference/index.mjs 55:11-23
Can't import the named export 'multiPolygon' from non EcmaScript module (only default export is available)
 @ ./node_modules/nebula.gl/dist-es6/lib/deck-renderer/deck-drawer.js
 @ ./node_modules/nebula.gl/dist-es6/index.js
 @ ./src/pages/demo.js
 @ ./src/root.js
 @ ./src/main.js
 @ ./node_modules/fusion-cli/entries/client-entry.js
 @ multi (webpack)-hot-middleware/client.js?name=client ./node_modules/fusion-cli/entries/client-entry.js
ERROR in ./node_modules/@turf/difference/index.mjs 54:41-48
Can't import the named export 'polygon' from non EcmaScript module (only default export is available)
 @ ./node_modules/nebula.gl/dist-es6/lib/deck-renderer/deck-drawer.js
 @ ./node_modules/nebula.gl/dist-es6/index.js
 @ ./src/pages/demo.js
 @ ./src/root.js
 @ ./src/main.js
 @ ./node_modules/fusion-cli/entries/client-entry.js
 @ multi (webpack)-hot-middleware/client.js?name=client ./node_modules/fusion-cli/entries/client-entry.js
```

Cursory search reveals this is probably a webpack problem. I noticed the examples all have a custom webpack config so that might be why it's not noticed.
https://github.com/Turfjs/turf/issues/1383

**Comment by georgios-uber** [comment] 2018-08-31 21:03
Seems like a fusion-app configuration issue.

**Comment by supersonicclay** [comment] 2018-09-02 06:46
I had issues with turf as well and fixed with yarn resolutions for now. I have this in my `package.json`:

```
"resolutions": {
    "@turf/bbox": "^5.1.5",
    "@turf/bbox-polygon": "^5.1.5",
    "@turf/buffer": "^5.1.5",
    "@turf/circle": "^5.1.5",
    "@turf/difference": "^5.1.5",
    "@turf/distance": "^5.1.5",
    "@turf/helpers": "^5.1.5"
  }
```

**Comment by georgios-uber** [comment] 2018-10-05 21:08
I spent some time today on this.
The issue is not with nebula but with turf (which is a nebula dependency) https://github.com/Turfjs/turf/issues/1383

`find . -name "*.mjs" | xargs rm` is a hacky 🔨  solution that solves the problem.

**Comment by lxe** [comment] 2019-09-04 23:38
If you're using next.js or vanilla webpack, or @lxe/fusion-cli, you can do what https://github.com/reactioncommerce/reaction-component-library/issues/399#issuecomment-467860022 recommends:

```js
    webpackConfig.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto'
    });
```

**Comment by rtsao** [comment] 2019-12-16 23:06
I created a PR to fix this upstream: https://github.com/Turfjs/turf/pull/1805

**Comment by georgios-uber** [comment] 2020-01-15 21:29
This is fixed now.

**Closed by georgios-uber** 2020-01-15 21:29 UTC
Labels: bug
