### ISSUE TITLE
Demo from readme broken

### ISSUE THREAD

**Issue by Akiyamka** [uber/nebula.gl#419] opened 2020-06-12 14:54 UTC
#### Describe the bug
https://codesandbox.io/s/admiring-shape-4dkyt
#### Actual Result
https://codesandbox.io/s/admiring-shape-4dkyt
#### Expected Result
Must work
#### Reproduce Steps
https://codesandbox.io/s/admiring-shape-4dkyt
#### Screenshots
![image](https://user-images.githubusercontent.com/6587585/84515944-ccab2080-acd5-11ea-8752-ffd2b650507b.png)

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by supersonicclay** [comment] 2020-06-12 20:22
This might be due to some broken version of one of nested dependencies under deck.gl. Any ideas @ibgreen or @Pessimistress?

**Comment by Pessimistress** [comment] 2020-06-15 19:30
Can't tell what broke from the log. Are you able to reproduce this locally?

**Comment by Akiyamka** [comment] 2020-06-23 08:28
Stack trace point to 
[https://4dkyt.csb.app/node_modules/deck.gl/geo-layers/dist/esm/h3-layers/h3-cluster-layer.js:22:18](https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/h3-layers/h3-cluster-layer.js#L22)

Localy this code crash with
```
./node_modules/@deck.gl/geo-layers/dist/esm/tile-3d-layer/tile-3d-layer.js
Attempted import error: 'Tileset3D' is not exported from '@loaders.gl/3d-tiles'. index.js:1437

./node_modules/@turf/difference/index.mjs
Can't import the named export 'diff' from non EcmaScript module (only default export is available) index.js:1437

./node_modules/@turf/difference/index.mjs
Can't import the named export 'feature' from non EcmaScript module (only default export is available) index.js:1437

./node_modules/@turf/difference/index.mjs
Can't import the named export 'flattenEach' from non EcmaScript module (only default export is available) index.js:1437

./node_modules/@turf/difference/index.mjs
Can't import the named export 'getGeom' from non EcmaScript module (only default export is available) 2 index.js:1437

./node_modules/@turf/difference/index.mjs
Can't import the named export 'multiPolygon' from non EcmaScript module (only default export is available) index.js:1437

./node_modules/@turf/difference/index.mjs
Can't import the named export 'polygon' from non EcmaScript module (only default export is available)
```

**Comment by supersonicclay** [comment] 2020-06-23 17:08
Created an issue upstream in deck.gl: https://github.com/visgl/deck.gl/issues/4711

**Comment by supersonicclay** [comment] 2020-06-25 15:01
A workaround for now is to change
```
import DeckGL from "@deck.gl";
```

to
```
import DeckGL from "@deck.gl/react";
```

**Comment by supersonicclay** [comment] 2020-06-26 19:37
This appears to be a CodeSandbox issue, and there's a workaround. Closing since it doesn't seem to be a nebula issue, but feel free to reopen if necessary.

CodeSandbox issue
https://github.com/codesandbox/codesandbox-client/issues/4476

**Closed** 2020-06-26 19:38 UTC
