### ISSUE TITLE
Dragging while drawing cancels drawing

### ISSUE THREAD

**Issue by yogurtandjam** [uber/nebula.gl#268] opened 2019-08-22 20:07 UTC
Currently, when the user is drawing a new geojson feature, if they move the mouse while clicking, the feature in drawing gets erased, as nebula registers this as a drag event. 

Using verison
Nebula version .11.2

#### Expected Result
user should be able to quickly draw new geojson features without having to make the mouse is completely still on every click

#### Reproduce Steps
create new editablegeojson layer in nebula, draw new feature quickly enough to trigger a drag event.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by supersonicclay** [comment] 2019-09-20 14:23
This could be due to passing in a new object to `EditableGeoJsonLayer` instead of using the same instance. Can you reproduce the behavior you're seeing with https://nebula.gl/geojson-editor/?

Here are some examples where you may see that kind of behavior:
```
render() {
  ...
  new EditableGeoJsonLayer({
    selectedFeatureIndexes: [],
    modeConfig: {}
  });
 ...
}
```

nebula.gl checks for shallow inequality to know when to reset its state and since it sees a new array/object each render cycle, that could clear the drawing.

**Comment by yogurtandjam** [comment] 2019-09-20 22:05
interesting - in the documentation the implementation looks like:
``` 
 render() {
    const layer = new EditableGeoJsonLayer({
      id: 'geojson-layer',
      data: this.state.data,
      mode: this.state.mode,
      selectedFeatureIndexes: this.state.selectedFeatureIndexes,

      onEdit: ({ updatedData }) => {
        this.setState({
          data: updatedData,
        });
      }
    });
```

but it seems like this is not the actual recommended approach.

the example geojson editor does not have this issue but it also a bunch more code than the documentation specifics - a lot of which i don't fully understand.

**Comment by supersonicclay** [comment] 2019-09-23 16:40
Using `selectedFeatureIndexes: this.state.selectedFeatureIndexes` works fine because the array is not re-created on every render. The issue is when you do `selectedFeatureIndexes: []` or `selectedFeatureIndexes: [0]` because `[]` in JavaScript creates a new object every time `render` is called by React. This can cause things inside nebula to re-render and potentially clear some state (e.g. the polygon being drawn).

**Comment by supersonicclay** [comment] 2020-01-14 22:09
Closing this issue. Feel free to re-open if you are still having an issue.

**Closed by supersonicclay** 2020-01-14 22:09 UTC
