### ISSUE TITLE
Minimum polygon drawing example not working

### ISSUE THREAD

**Issue by vnugent** [uber/nebula.gl#141] opened 2018-12-09 21:21 UTC
#### Describe the bug
I'm trying to create a minimal working example to experiment with draw polygon.  However the code seems to work sporadically.  See code sandbox link below.

Mouse actions resulting in errors:
1. Immediately double-click
2. Click once, move mouse, then double-click

Mouse actions that work sporadically:
1. Draw at least 2 nodes, then double-click to complete the polygon
2. Draw at least 3 nodes, then click/double-click first node 

https://codesandbox.io/s/3192o0kjj5?module=%2Fsrc%2FApp.jsx

it seems bad json data is being passed to Deck.gl
![deck gl error](https://user-images.githubusercontent.com/3805254/49703063-1bde3580-fbb5-11e8-93d7-638e9edf3e9d.png)

![nebula gl edit-error](https://user-images.githubusercontent.com/3805254/49703071-331d2300-fbb5-11e8-8cd6-cbcdff5e7bbf.png)

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by georgios-uber** [comment] 2018-12-10 19:17
Can you paste the data you are providing in "data" field? It has to be a feature collection.

**Comment by vnugent** [comment] 2018-12-10 19:23
The data should be initialized to an empty Feature collection as shown in the code

**Comment by georgios-uber** [comment] 2018-12-10 19:30
Double clicking "finalizes" the polygon. So if you add two points, that results in an invalid polygon.
I will write a check to avoid that.

**Comment by georgios-uber** [comment] 2018-12-10 19:30
Also, You need to provide a mapbox token to see the map under.

**Comment by vnugent** [comment] 2018-12-10 19:38
Yes, I do have a Mapbox layer in my app. I just waned to simplify things for codesandbox

**Comment by carlostxm** [comment] 2019-01-21 13:55
I am having the same problem, in drawPolygon mode when the first action is double click or double clicking after set a first point results in a weird state: two points without line are painted without calling to onEdit callback. 

Is there any advance on this issue?

**Comment by carlostxm** [comment] 2019-01-22 08:21
> Double clicking "finalizes" the polygon. So if you add two points, that results in an invalid polygon.
> I will write a check to avoid that.

Hi @georgios-uber, is it planned to include this validation soon?

**Comment by supersonicclay** [comment] 2019-01-25 17:01
This may be a duplicate of #153. If you're using deck 6.3, you'll need to upgrade nebula to 0.8. Or you can downgrade deck to <6.3.

Sorry for the inconvenience. There was an unintended function name collision.

**Comment by georgios-uber** [comment] 2019-01-28 22:40
@carlostxm please close the issue if updating fixes this.

**Comment by supersonicclay** [comment] 2019-01-29 15:27
@vnugent if upgrading to nebula 0.8 fixes it, can you close this issue?

**Comment by vnugent** [comment] 2019-01-29 19:42
It's still not behaving the way I think it should.  It now lets me create a single-point polygon (all 4 vertices are the same) or a "line" polygon (2 vertices are the same).  Another word `addFeature` event is generated if I simply double click or draw a line then double click.   See code sandbox link.

https://codesandbox.io/s/wk56rvzjl7

```
    "deck.gl": "6.3.9",
    "nebula.gl": "0.8",
    "nebula.gl-react": "0.8",
```

**Closed** 2019-01-30 02:55 UTC
Labels: bug

**Comment by supersonicclay** [comment] 2019-01-30 02:56
Nice find!
